### ISSUE TITLE
Any method not working

### ISSUE THREAD

**Issue by ghost** [miladrahimi/phprouter#10]
Any method isn't working, give me "Methods must be set in" error
$router->any("/", function () {
    echo 'Hello';
});

And i liked this library, very lite and perfect syntax.

Thanks...

**Comment by miladrahimi** [comment]
Your pull request is merged and new version `v2.3.6` is released now. Of course, the new version which is coming tomorrow, you should consider an update, it's fully redesigned and use Psr7 HTTP request and response, unit tests are also used.
