### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by mafio69** [miladrahimi/phprouter#13]
This error pops up as there is no correct route, is it supposed to be this way?

Fatal error: Uncaught MiladRahimi\PhpRouter\Exceptions\RouteNotFoundException in I:\www\udemy\vendor\miladrahimi\phprouter\src\MiladRahimi\PhpRouter\Router.php:225 Stack trace: #0 I:\www\udemy\Public\index.php(50): MiladRahimi\PhpRouter\Router->dispatch() #1 {main} thrown in I:\www\udemy\vendor\miladrahimi\phprouter\src\MiladRahimi\PhpRouter\Router.php on line 225

**Comment by miladrahimi** [comment]
You should catch this type of exception and display your design of 404 page.

**Comment by mafio69** [comment]
Thanks
