### ISSUE TITLE
Is it?

### ISSUE THREAD

**Issue by mafio69** [miladrahimi/phprouter#14]
Is it? Possibility to add routes in the array or some list?

**Comment by miladrahimi** [comment]
Could you explain more and write a sample?

**Comment by mafio69** [comment]
E.g
[
'/tets/{23}' => 'StartController@index',
'/tets/two' => 'StartController@show',
]
and inject this array into the object.
Besides, great work!

**Comment by miladrahimi** [comment]
Not actually, this feature couldn’t be beneficial.
