### ISSUE TITLE
Support for nested groups

### ISSUE THREAD

**Issue by dak4mi** [miladrahimi/phprouter#15]
Hey,
first of all thank you for this great library, it's really easy to work with.
The problem I encountered is that i can't nest groups properly:
```
$router->group(['prefix' => '/api', 'middleware' => $middleware], function (Router $router) {
	// /api/test/ - unreachable
	$router->group(['prefix' => '/test'], function (Router $router) {
		$router->get('/', TestController::class);
	}
	// /api/api/ - reachable?! 
	$router->group(['prefix' => '/api'], function (Router $router) {
		$router->get('/', TestController::class);
	}
}
```
Tested with 3.0.4.
Is there any chance to support nested groups?

Cheers
dak4mi

**Comment by miladrahimi** [comment]
Thanks for your reporting.
Currently, I work on a new version of this package, I'll consider this feature in the new version.

**Comment by miladrahimi** [comment]
You can check the new version.
