### ISSUE TITLE
Linking Middleware to an external file

### ISSUE THREAD

**Issue by itzzpadre** [miladrahimi/phprouter#17]
Hello hope this can get answered i have recently found your script and i think its amazing my issue is 

when i place the middleware class within my routing files called web.php it runs the middleware script however if i do the following 

$router->get('/users', 'Users@index',\App\Middleware\AuthMiddleware::class);

im getting this 

 Fatal error: Uncaught MiladRahimi\PhpRouter\Exceptions\InvalidMiddlewareException: Invalid middleware for route: {"name":null,"uri":"\/users","method":"GET","controller":"App\\Models\\Users@index","middleware":["App\\Middleware\\AuthMiddleware"],

any help would be greatly appreciated

**Comment by miladrahimi** [comment]
Hello,
Could you please put your codes (middleware, directory structure, etc.) here?
There some tests for the middleware https://github.com/miladrahimi/phprouter/blob/master/tests/MiddlewareTest.php and it shows that the router supports middleware classes everywhere.

**Comment by itzzpadre** [comment]
![image](https://user-images.githubusercontent.com/30671636/66812203-5b3e8680-ef2a-11e9-8485-7e0d4aca7077.png)



So following your examples i created a simple redirect with no checking  now if i simply include the file 


<?php 
namspace App\Middleware
use MiladRahimi\PhpRouter\Middleware;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

class Auth implements Middleware
{
    public function handle(ServerRequestInterface $request, Closure $next)
    {
        header("location:/auth");
        return $next($request);
    }
}

<?php

use MiladRahimi\PhpRouter\Router;
use Zend\Diactoros\Response\HtmlResponse;
use Zend\Diactoros\Response\JsonResponse;


$router = new Router('', 'App\Models');
$router->get('/auth', function () { return 'OK'; });

$router->get('/', function () {
    return '<p>This is homepage!</p>';
});

$router->get('/users', 'Users@index',App\Middleware\Auth::class);
$router->post('/users/Store', 'Users@Store');
$router->dispatch();

so after a bit of experimenting last night  i found that if i removed the namespace and dont call by namespace and use and include file directly it calls the middleware 

as i saiid including files works calling namespace method doesnt even if i was to call App\Middleware\Auth and then call the middleware as Auth::class

thanks again

**Comment by miladrahimi** [comment]
Could you explain more, please? Is there still an issue?
If you use composer autoload no need to require/include anything manually.

**Comment by itzzpadre** [comment]
yes theres still an issue i have used dump autoload and it still causes this issue
thanks fir your response here is an image of my strucutre

![image](https://user-images.githubusercontent.com/30671636/66812654-3d255600-ef2b-11e9-885b-1fe5faadda38.png)

here is a screen of my web.php
![image](https://user-images.githubusercontent.com/30671636/66812708-5201e980-ef2b-11e9-90db-9847a74c55df.png)

here is a pictiure of my auth middleware script

![image](https://user-images.githubusercontent.com/30671636/66812759-6a720400-ef2b-11e9-8b1c-979e7ebefca5.png)

Now if i run it usingh the include file as above it will call the middleware no problem

now when i add namespace App\Middleware  to Auth.php
and use App\Middleware\Auth in web.php

i ghet this error

![image](https://user-images.githubusercontent.com/30671636/66813489-c5582b00-ef2c-11e9-8b53-1a93d716858e.png)

web.php
![image](https://user-images.githubusercontent.com/30671636/66813598-f2a4d900-ef2c-11e9-8f23-e0a0339e11ce.png)

**Comment by miladrahimi** [comment]
The issue is not about PhpRouter, it belongs to abusing PHP namespaces!
The middleware you have implemented has no namespace and you should add it this way:
```
<?php

namespace App\Middleware;

...

```

**Comment by itzzpadre** [comment]
yes theres still an issue i have used dump autoload and it still causes this issue
thanks fir your response here is an image of my strucutre

![image](https://user-images.githubusercontent.com/30671636/66812654-3d255600-ef2b-11e9-885b-1fe5faadda38.png)

here is a screen of my web.php
![image](https://user-images.githubusercontent.com/30671636/66812708-5201e980-ef2b-11e9-90db-9847a74c55df.png)

here is a pictiure of my auth middleware script

![image](https://user-images.githubusercontent.com/30671636/66812759-6a720400-ef2b-11e9-8b1c-979e7ebefca5.png)

Now if i run it usingh the include file as above it will call the middleware no problem

now when i add namespace App\Middleware  to Auth.php
and use App\Middleware\Auth in web.php

i ghet this error

![image](https://user-images.githubusercontent.com/30671636/66813489-c5582b00-ef2c-11e9-8b53-1a93d716858e.png)

web.php
![image](https://user-images.githubusercontent.com/30671636/66813598-f2a4d900-ef2c-11e9-8f23-e0a0339e11ce.png)

**Comment by itzzpadre** [comment]
yep ive already done that 

![image](https://user-images.githubusercontent.com/30671636/66814705-fa657d00-ef2e-11e9-987e-ebdd65e0dd1c.png)

and still getting same error

**Comment by miladrahimi** [comment]
Now if you check your IDE hints, Closure class is declared under \ namespace, so you have to add a use statement for it or you can add \ before it to use it. \Closure

**Comment by itzzpadre** [comment]
I.will look at this later thanks for your help I'll get back to you later
today

**Comment by itzzpadre** [comment]
Ok so thanks for your support andas i said its an amazing script you have wrote  kudos to you the /closure worked and thanks for that peice of informarmation

**Comment by itzzpadre** [comment]
sorry i do have one question with this script does it have the ability to use the name as a url forwarder like laravel does when it used router(user.post) for example

**Comment by miladrahimi** [comment]
Yes, https://github.com/miladrahimi/phprouter#route-name
