### ISSUE TITLE
Possibility to add response cookies before sending $next($request)

### ISSUE THREAD

**Issue by gergokee** [miladrahimi/phprouter#19]
Currently  $next($request) can't be intercepted, would be nice to be able to intercept and add header cookies to the response for example.

**Comment by miladrahimi** [comment]
Something like this is still possible:
```
class MyMiddleware implements Middleware
{
    public function handle(ServerRequestInterface $request, Closure $next)
    {
        /** @var ResponseInterface $response */
        $response = $next($request);
        
        return $response->withHeader('MyHeader', 'MyValue');
    }
}
```
Doesn't it handle your requirements?

**Comment by gergokee** [comment]
Well, for me it is not returning any header, and this line is returning response, without calling "return": $response = $next($request);
As i said i'm unable to intercept the $response, what am i missing?

**Comment by miladrahimi** [comment]
If you want to return something else instead of controller response see this:

```
class MyMiddleware implements Middleware
{
    public function handle(ServerRequestInterface $request, Closure $next)
    {
        /** @var ResponseInterface $response */
        $response = $next($request);
        // Do something with the $response or ignore it
        return 'What I like to return instead of original response';
    }
}
```

Maybe I'm mistaken so please send the code in your mind that you think it should work.

**Comment by gergokee** [comment]
This is my code:

```
namespace Classes\Middlewares;
use MiladRahimi\PhpRouter\Middleware;

use Closure;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Message\ResponseInterface;


class TesterMiddleware implements Middleware
{

    /**
     * Handle an incoming request.
     *
     * @param  \Psr\Http\Message\ServerRequestInterface  $request
     * @param  \Closure  $next
     * @return mixed
     *
     */
    public function handle(ServerRequestInterface $request, Closure $next)
    {

        /** @var ResponseInterface $response */
        $response = $next($request);
        // Do something with the $response or ignore it
        return 'What I like to return instead of original response';
        
    }


}
```
The returns the **next request** instead of 'What I like to return instead of original response'

Maybe the problem is with zend-diactoros, i found here:
https://github.com/zendframework/zend-diactoros/issues/75

And then i have to use a a cookie library...

**Comment by gergokee** [comment]
Problem solved, i did not use  ResponseInterface $response  how it should be used... (I'm testing several php routers' performances and made mistakes.) Thank you for this nice job and sorry for spending your time :)
