### ISSUE TITLE
Validate Inputs

### ISSUE THREAD

**Issue by lucacastelnuovo** [miladrahimi/phprouter#21]
Would it be possible to add Laravel like input validation to this?

```php
$this->validate($request, [
    'title' => 'required|unique:posts|max:255',
    'body' => 'required',
]);
```

How would you recommend doing this?

**Comment by miladrahimi** [comment]
Unfortunately, PhpRouter is an HTTP router not a full-featured framework like Laravel. You should find an appropriate validator package for it.
