### ISSUE TITLE
ServerRequest in constructor

### ISSUE THREAD

**Issue by lucacastelnuovo** [miladrahimi/phprouter#23]
Is this possible?

I get this error `Fatal error: Uncaught ArgumentCountError: Too few arguments to function App\Controllers\Controller::__construct(), 0 passed ...`

```php
class Controller
{
    protected $request;

    /**
     * Provide access for child classes
     * 
     * @return void
     */
    public function __construct(ServerRequest $request)
    {
        // Load request
        // $this->request = $request;
    }
}
```

**Comment by miladrahimi** [comment]
Currently router only inject request, response and the router itself only to the controller method related to the current route.
You can send pull request for this feature or wait for the next version

**Comment by lucacastelnuovo** [comment]
I've taken a quick glance at the code and I don't think I can help you with this. Thank you for all the quick responses.

**Comment by miladrahimi** [comment]
I'll consider it for the next version.
Your welcome.

**Comment by miladrahimi** [comment]
This feature is added in version 5.
