### ISSUE TITLE
Get requestpath with variables

### ISSUE THREAD

**Issue by lucacastelnuovo** [miladrahimi/phprouter#26]
Would it be possible to have an `$request->getUri()` alternative that returns the base path.

Example:
1. Request to the route `/example/{var}` with `/example/123`
2. `$request->getUri()` returns `/example/123`

How would I get the original base (`/example/{var}`)? Maybe `$request->getBase()`?

**Comment by miladrahimi** [comment]
Currently, this feature is no available. Could you please explain why do you need this feature and what's your use case?

**Comment by lucacastelnuovo** [comment]
I'm trying to create ratelimit middleware (https://github.com/Luca-Castelnuovo/CubeQuence-framework/blob/master/src/CubeQuence/Middleware/RateLimit.php). And I would like to be able to have multiple limits set for multiple endpoints.

For the following example:
```php
$router->get('/foo', 'ExampleController@foo', RateLimit::class); // 45 requests / 60 seconds
$router->get('/bar', 'ExampleController@bar', RateLimit::class); // 10 requests / 5 seconds
```

I was planning to achieve this by getting the request path
```php
$path = $request->getUri();
$path = strtok($path, '?');
$path = strtok($path, '#');
```

And then lookup aan associative array
```php
$path = Request::path($request);

$this->max_requests = (int) Config::get("ratelimit.{$path}.max_requests") ?: 60;
$this->reset_time = (int) Config::get("ratelimit.{$path}.reset_time") ?: 60;
```

This would work fine if I didn't use URL params. Because if you use the following:
```php
$router->get('/fooBar/{uuid}', 'ExampleController@foo', RateLimit::class); // 45 requests / 60 seconds
```

I wouldn't be able to create an config entry for each uuid.
So if I could get the basepath like:
```php
$basePath = Request::basePath($request);

$this->max_requests = (int) Config::get("ratelimit.{$basePath}.max_requests") ?: 60;
$this->reset_time = (int) Config::get("ratelimit.{$basePath}.reset_time") ?: 60;
```

I could configure limits for each route.

**Comment by miladrahimi** [comment]
Thanks for your suggestion, I'm working on the next major version of PhpRouter, I will consider this feature.

**Comment by miladrahimi** [comment]
This feature is added to the last release. Please check:
https://github.com/miladrahimi/phprouter#current-route
