### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by itzzpadre** [miladrahimi/phprouter#30]
Hi I was wondering is there a way in your code to stop it giving the scripts error message for example if i tell it i was int values only on the routing and i   type string i get uncaught errors anyway i can formward this to a 404 page etc

**Comment by miladrahimi** [comment]
As far as i understood you pointed to three concepts: route parameter patterns, error handling and 404 errors.

If you want to declare a route parameter to limit the parameter value you can see the following example:
```php
// id must be a number!
// It raises RouteNotFoundException if user enter non-numeric value for id
$router->pattern('id', '[0-9]+');

$router->get('/post/{id}', function (int $id) {
    return 'Content of the post: ' . $id;
});
```

You can raise any exceptions in your code/controllers/middleware and catch them like this:
```php
$router->get('/', function () {
    throw new MyCustomException();
});

try {
    $router->dispatch();
} catch (MyCustomException $e) {
    // Log and report the error...
    $router->getPublisher()->publish(new HtmlResponse('Internal error.', 500));
}
```

As for  404 pages you should catch `RouteNotFoundException` like this:

```php
$router->get('/', function () {
    return 'Home.';
});

try {
    $router->dispatch();
} catch (RouteNotFoundException $e) {
    // If compiler is here, it means user  wants a page that does not exist
    // Show your 404 page or use something like this:
    $router->getPublisher()->publish(new HtmlResponse('Not found.', 404));
}
```

**Comment by itzzpadre** [comment]
Thank you for your reply I will try that I think that should work thanks
again

**Comment by itzzpadre** [comment]
I want to say thanks for your reply the other day i have finally tried the code you provded and it works a charm

**Comment by miladrahimi** [comment]
You can star the repository if you liked it ;)

**Comment by itzzpadre** [comment]
I think I already have :)
