### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by itzzpadre** [miladrahimi/phprouter#34]
Hello am following your guide on middleware i am creating a class for middleware rather than storing it in the routes web file and im getting this error

![image](https://user-images.githubusercontent.com/30671636/108592618-a6f71080-7366-11eb-888f-d898148cf4ca.png)

here is my code

![image](https://user-images.githubusercontent.com/30671636/108592631-b5452c80-7366-11eb-99ab-94194cd87a46.png)

am i missing something thanks  again

**Comment by itzzpadre** [comment]
Scrap this i needed to add the /closure classs into the use case :)

**Comment by miladrahimi** [comment]
It's better to have a class for middleware instead of  Closure.
The problem with the code above is that you should add a `\` before Closure or import it (`use Closure`).
PhpStorm also has warned you that you haven't import Closure class.

**Comment by itzzpadre** [comment]
Yh I managed to fix it afterwards thanks for your help either way  so do I
just create a middleware class rather than separate classes for separate
middleware

**Comment by miladrahimi** [comment]
In the prev message, I said that class is better than closure for middleware, but separating middleware and overall separation is a good practice ;)

**Comment by itzzpadre** [comment]
Yh that's great thanks for your help I worked out the closure in the end
