### ISSUE TITLE
Obtaining QueryString Data

### ISSUE THREAD

**Issue by itzzpadre** [miladrahimi/phprouter#35]
cant see it in your documentation but does the routing support using ?keyword=mike  im trying to setup a search page for users and it doesnt seem to be picking up and results to the catch and gives my custom error page which is just page not found

my form path is : /admin/search and then as a get method throws up ?keyword=

my route at the moment as i thought it might work is /admin/search/?keywork={keyword}

tia

**Comment by miladrahimi** [comment]
Hello,
The `?keyword=mike` and everything after `?` is called Query String and is not part of the route.
As for your search route `/admin/search?keywork={keyword}`, the route should be `/admin/search` and it can be mapped to controller like `SearchController::index()`.
To catch the query string (`keywork={keyword}`) you can do something like the following code:

```php
use Laminas\Diactoros\ServerRequest;

class SearchController {
    function index(ServerRequest $request) {
        $keyword = $request->getQueryParams()['keyword'];
        // Search $keyword in database or anywhere else...
        // return response as view or json, etc.
    }
}
```

**Comment by itzzpadre** [comment]
Great thank you I will look at that later

**Comment by itzzpadre** [comment]
Hi So as of now i am still using your Router ive been out of it for a while however it seems that  $keyword = $request->getQueryParams()['keyword']; this no longer works ansd gives Undefined array key "id" , i have changed the word keyword to id.

i have tried wrapping it in an iseset and nothing seems to be changing has something changed on yours or laminas side for this to not work anymore

**Comment by miladrahimi** [comment]
what do u get when print_r($request->getQueryParams()) ?

**Comment by itzzpadre** [comment]
![image](https://user-images.githubusercontent.com/30671636/211154428-d3075f2e-6fe4-4399-957f-4f3ba475f838.png)

heres the address bar snippet
![image](https://user-images.githubusercontent.com/30671636/211154471-33ea1816-5344-4925-9cbe-130f06bdfc7d.png)

and my code

![image](https://user-images.githubusercontent.com/30671636/211154494-9bca042b-5e24-41d2-8086-241a25ebfa5a.png)
