### ISSUE TITLE
Question Again

### ISSUE THREAD

**Issue by itzzpadre** [miladrahimi/phprouter#36]
I am looking at your examples and this one in question 

$router = Router::create();

$router->get('/about', [AboutController::class, 'show'], 'about');
$router->get('/post/{id}', [PostController::class, 'show'], 'post');
$router->get('/links', function (Url $url) {
    return new JsonResponse([
        'about' => $url->make('about'),             /* Result: /about  */
        'post1' => $url->make('post', ['id' => 1]), /* Result: /post/1 */
        'post2' => $url->make('post', ['id' => 2])  /* Result: /post/2 */
    ]);
});

$router->dispatch();

when i follow the links /links i  get the json information when i go /links/about or admin in my case it says page not found(my cyustom error handler)

how would i get this to redirect to the page in querstiuon also  where the [id =>1] can this take variables 

im sorry for the all the questions i really appreciate this script that you have done as its really amazing i would always recommend this

tia

**Comment by miladrahimi** [comment]
The error occurs when PhpRouter cannot find a route with the given name, so make sure your routes have name when you use `Url::make()` method. Just like the example, there is two routes defined, about and post, about route is simple but post route has a paramater so when you call `Url::make()` you have to pass the appropriate value for the route paramter. If it didn't help you please insert your routes list and the related controller code in the reply.

**Comment by itzzpadre** [comment]
hi thanks for the response i have actually put my own route in and the address url i set to link does that need to match an exisiting route

heres my routes with a name of gallery

![image](https://user-images.githubusercontent.com/30671636/112538171-7d873580-8da7-11eb-8a78-6ce923b5c5d9.png)
here is the view when i go to /links

![image](https://user-images.githubusercontent.com/30671636/112538212-8a0b8e00-8da7-11eb-9a34-6d45d4fd67d4.png)


heres where the confusion is on how i access that page using the name or using an a link

![image](https://user-images.githubusercontent.com/30671636/112538331-a8718980-8da7-11eb-8e0c-194bc86b21c2.png)

i want to know how i make that route on the json redirect to the page in question

**Comment by itzzpadre** [comment]
Also can i use {id} {username }  etc within the json links

**Comment by miladrahimi** [comment]
As for the generated link, the gallery route path has the `{username}` parameter so when you wanna make its url, you should pass a value for it like this:
```php
echo $url->make('gallery', ['username' => 'jack']); // Result: /profile/jack/gallery
```

As for the not found page, the URL is `/links/gallery`, there is no such route in your routes, don't know where have you made that.

You might misunderstand the named routes feature.
Named Routes feature is for making the code depneded to the names instead of URLs.

For example if we have this route:

```
$router->get('/blog/posts/{pid}/comments/{cid}/edit', [PostsController, 'show'], 'blog.posts.comments.edit');
```

To generate `/blog/posts/13/comments/666/edit`,

Your code could be:
```php
$link = str_replace('/blog/posts/{pid}/comments/{cid}/edit', '{pid}', 13);
$link = str_replace($link, '{cid}', 666);
```
or could be:
```php
$url->make('blog.posts.comments.edit', ['pid' => 13, 'cid' => 666]);
```

So it's about generating links not redirecitng.

Please let me know if your problem is not solved yet.

**Comment by itzzpadre** [comment]
Heya again thanks for your response I understand the named routes are
basically supposed to pull  the named controller.


The username is pulls from the get value in from the website using
{username) as described in your documentation

I think the confusion in having is how I call the link I just made for
example

Laravel required you to add rout(routename) and it's variables to go to the
page in question  I think that's where I'm misunderstanding it

Do the JSON results replace my existing routes or is it right where I have
put them

I understand the logic just struggling on how to call them and if the
username is dynamic can that be called dynamically or do I have to manually
add usernames and ids

**Comment by miladrahimi** [comment]
Named routes has no direct relation with controllers, it's just for setting a name for a route, then using name in your codes instead of URLs.

What do you mean by "call"?

Do you want to redirect to a route?
```php
use Laminas\Diactoros\Response\RedirectResponse;

$router->get('/dashboard', function() { /* ... */ }, 'dashboard');
$router->get('/login', function() { /* ... */ });
$router->post('/login', function (URL $url) {
    // If username and password is ok then:
    return new RedirectResponse($url->make('dashboard'));
});
```

Do you want have the link in the view layer:
```php
use MiladRahimi\PhpRouter\Url;
use MiladRahimi\PhpRouter\View\View

class HomeController {
    public function show(Url $url, View $view) {
        return $view->make('home', ['url' => $url]);
    }
}
```
```html
<a href="<?php echo $url->make('profile') ?>">Profile</a>
```

If you something else, please put the laravel code you mean then I can change it to PhpRouter ;)

**Comment by itzzpadre** [comment]
Thanks what I'll do.ill try it I think I get the idea its using blade
template but isn't using laravel directly but if I will try it and If I
have issues I'll come.back

Thanks for.taking the time  to help me

**Comment by itzzpadre** [comment]
So i found a solution which i think is the same as what laravel and other framework do is the following.

![image](https://user-images.githubusercontent.com/30671636/112704275-e945cd00-8e91-11eb-864d-6e9f52eb8661.png)

i was reading your code litterly as thats how it was supposed to be done in json thats my bad  also i got myself confused on how to output the result so i could use it in a hyperlink or  form data output,

what i was trying to do was pull the get value from {username} in my blade templating which wasnt possible anyway my solution was to pull $user->username  in your code which  works.



sorry for being a pain i really appreciate the work you have done here is a really decent little router.

just out of curiosity would it not be better to name make() as route() or would that just be to confusing :)

thanks for your time and patience with me i know what im doing now

**Comment by miladrahimi** [comment]
You are very welcome, it makes happy when it seems useful to someone.
As for naming suggestion, actually, if it was a helper function the name `route()` would be better but it's a method of the class `Url` so I think `Url::make()` makes more sense than `Url::route()` while Url and route are almost the same entity :)
But I would be happy to hear your ideas to make the package even better.

**Comment by itzzpadre** [comment]
To be honest I don't really think it needs improving much it works really
well  I i think everything in the script is covered  nearly I I do.think of
anything I'll come back with suggestions

**Comment by itzzpadre** [comment]
Sorry again to open this i have no issues but i did come up with a suggestion if you think it would work and if you implement it to the system (it may be unrelated) but i was working on my project today and i thought about the routing names and a breadcrumb feature.

would this be possible is it something that might be worth looking into ??

**Comment by miladrahimi** [comment]
As far as I know, breadcrumb is completely a view layer problem, would you please tell me what's you idea?
 for example the code (method) you believe should be there in Router class

**Comment by mbamber1986** [comment]
hi @miladrahimi  thanks for your response ive only just seen this and wasnt notified as the issue is closed but my idea was  like the  your url method 
url->make() and you pass url url etc

the breadcrumb on the router side would pull each directory path you create in the router so lets say  

$router->get("/admin/users/home.function(),"name") obviously would have to support the group prefix as well 

and then splits it after each / and can be passed into the view and its loaded on the view end

that would be my idea.

sorry if anything there is a bit confusing but this was my thinking

you think its possible
