### ISSUE TITLE
Is it possible to pass parameters to middleware?

### ISSUE THREAD

**Issue by lucacastelnuovo** [miladrahimi/phprouter#38]
```php
$router->group(['middleware' => [AuthMiddleware::class]], function(Router $router) {
    $router->get('/admin', function () {
        return 'Admin API';
    });
});
```

If I wanted to pass some parameters to AuthMiddleware, for example requiredGroup='admin', how could I do this?

**Comment by miladrahimi** [comment]
Unfortunately this feature is not availabe yet. You can create a pull request for it or wait for next version.

**Comment by lucacastelnuovo** [comment]
Okay, I will wait
