### ISSUE TITLE
undefined index QUERY_STRING in Request.php on line 131

### ISSUE THREAD

**Issue by alpe89** [miladrahimi/phprouter#4]
If you have a get request with no querystring php will write a 
`Notice: Undefined index: QUERY_STRING in ..\vendor\miladrahimi\phprouter\src\MiladRahimi\PHPRouter\Request.php on line 131`

I think that you should just add a default value if $_SERVER['QUERY_STRING'] does not exists.

**Comment by miladrahimi** [comment]
@Froz89 
Could u send a pull request, I would merge it if it was appropriate.
