### ISSUE TITLE
About $url->make()

### ISSUE THREAD

**Issue by itzzpadre** [miladrahimi/phprouter#40]
Hi again i was just wondering can i use $url->make("address.page",['usernarmae'=>$username]) go to a post variable or  is this only set up  to do get variables if so do you have anyway in your script that can pull / http Post requests

**Comment by miladrahimi** [comment]
The Url::make() is used to generate URLs from route names to avoid hard-coding URLs in code layer.
For example:
```php
$postUrl = $url->make('blog.post', ['id' => $postId]);
```
instead of:
```php
$postUrl = '/blog/post/' . $postId;
```

**Comment by itzzpadre** [comment]
Ok thasnks im going to assume though once passed  it will turn into a get request

i wanted to know if it would stay as a  post request for submission

its not an issue 

thanks for your hard work its much appreciated
