### ISSUE TITLE
Question about obtaining list or urls from web file and the method type

### ISSUE THREAD

**Issue by itzzpadre** [miladrahimi/phprouter#42]
Hello again my friend i have a question more of an issue, still loving your router heres the case of use

i am planning on building a roles, and rules system for  my website and i want to base it on the url  that it is currently at.

so in this case i i can pull all the array values from $url, and the current value if i was to use ROUTE  anyway i need to know if there is anyway i can simply pull just the path and the type of method it is 

so i can do soemthing like this in kmy admin panel 

foreach($url as $path)
{
echo "Path : $path['path'] . "Add rules" . "Method type " . $path['method']
}

i litterly need to detect the url  and the method post get etc

and the rest i will do via middleware 

thanks in advance

**Comment by miladrahimi** [comment]
Hello. Thanks for your using the package.
Please update to the latest version if you haven't already.
Read the following section of the package README.
https://github.com/miladrahimi/phprouter#current-route
It illustrates all the available information that a route object provides.
You probably need the "path" and "method" attributes.

**Comment by itzzpadre** [comment]
Hi thanks for your response and your example

The one you gave me I found only pulls rhe current route

As I said if I use print_r($url) I get rhe list off All data including the
url the name and the method but if I do $url ijna for each loop adding path
and method it doesn't display anything when echoing

I need to display all the admin routes listed inside the web routing file


Tia

**Comment by miladrahimi** [comment]
If you mean something like `$router->all()` to get all the registered routes, no but I can implement it for you.
You can create a ACL middleware to check user access like this {

```
use MiladRahimi\PhpRouter\Routing\Route;
use Psr\Http\Message\ServerRequestInterface;

class AclMiddleware
{
    public function handle(ServerRequestInterface $request, Closure $next, Route $route)
    {
        // Find the current user => $user
        if ($user->can($route->getPath())) {
            return $next($request);
        }

        return new JsonResponse(['error' => 'ACL Error!'], 403);
    }
}
```

**Comment by itzzpadre** [comment]
Thanks yh the idea of all() was what I was aiming for I just need to find
away to auto register the routes  somehow as I want to implement and roles
and permissions system to that
ent it?
Thanks anyway

Love this script been working with it  for last year

Any way or any plans to implement it

**Comment by miladrahimi** [comment]
https://github.com/miladrahimi/phprouter/releases/tag/5.1.1

**Comment by miladrahimi** [comment]
update to this version and you can call $router->all().
Btw, you can get the router object in your middleware and controllers using controller or middleware parameters. it injects the object automatically.

**Comment by mbamber1986** [comment]
Will I be able to get the path and method from that

Thanks again

Your great

**Comment by itzzpadre** [comment]
So i have checked it i can work with this you have been great and very accomadatng to this request thanks again :)
