### ISSUE TITLE
Uncaught ReflectionException

### ISSUE THREAD

**Issue by maximcs1** [miladrahimi/phprouter#44]
if route contains name of functions (like count, current etc) then i have that error

> Fatal error: Uncaught ReflectionException: Cannot determine default value for internal functions in B:\OpenServer\domains\region.loc\vendor\miladrahimi\phpcontainer\src\Container.php:191 Stack trace: #0 B:\OpenServer\domains\region.loc\vendor\miladrahimi\phpcontainer\src\Container.php(191): ReflectionParameter->getDefaultValue() #1 B:\OpenServer\domains\region.loc\vendor\miladrahimi\phpcontainer\src\Container.php(164): MiladRahimi\PhpContainer\Container->resolveParameters() #2 B:\OpenServer\domains\region.loc\vendor\miladrahimi\phpcontainer\src\Container.php(110): MiladRahimi\PhpContainer\Container->call() #3 B:\OpenServer\domains\region.loc\vendor\miladrahimi\phpcontainer\src\Container.php(181): MiladRahimi\PhpContainer\Container->get() #4 B:\OpenServer\domains\region.loc\vendor\miladrahimi\phpcontainer\src\Container.php(164): MiladRahimi\PhpContainer\Container->resolveParameters() #5 B:\OpenServer\domains\region.loc\vendor\miladrahimi\phprouter\src\Dispatching\Caller.php(111): MiladRahimi\PhpContainer\Container->call() in B:\OpenServer\domains\region.loc\vendor\miladrahimi\phpcontainer\src\Container.php on line 166

example:
`$router->get('/catalog/{name}', [CatalogController::class]);`
and if go to localhost/catalog/count or localhost/catalog/current we get this error

**Comment by miladrahimi** [comment]
Thanks for your report. Please update to 5.1.3
https://github.com/miladrahimi/phprouter/releases/tag/5.1.3
