### ISSUE TITLE
اجرای route بعدی

### ISSUE THREAD

**Issue by 1mahdimf** [miladrahimi/phprouter#45]
سلام 
من کدی نوشتم که ادرس های که اخرشون اسلش / داره رو به بدون اسلش هدایت کنه.
` $router->get('(.*)', function ....`

می خوام بعضی وقت ها که نیاز به هدایت نیست route بعدی اجرا بشه. و این رو نادیده بگیره.
ممنون میشم راهنمایی کنید.

**Comment by miladrahimi** [comment]
سلام واسه اینکار بهتره میدلور بسازی و همه روت هاتو توی یه گروپ بذاری با اون میدلور. توی میدلور ریکوست رو چک کنی.
