### ISSUE TITLE
QueryStringData Revisited

### ISSUE THREAD

**Issue by itzzpadre** [miladrahimi/phprouter#49]
Hi So as of now i am still using your Router ive been out of it for a while however it seems that  $keyword = $request->getQueryParams()['keyword']; this no longer works ansd gives Undefined array key "id" , i have changed the word keyword to id.

i have tried wrapping it in an iseset and nothing seems to be changing has something changed on yours or laminas side for this to not work anymore

_Originally posted by @mbamber1986 in https://github.com/miladrahimi/phprouter/issues/35#issuecomment-1374486116_

**Comment by miladrahimi** [comment]
what do u get when print_r($request->getQueryParams()) ?

**Comment by itzzpadre** [comment]
![image](https://user-images.githubusercontent.com/30671636/211154428-d3075f2e-6fe4-4399-957f-4f3ba475f838.png)

heres the address bar snippet
![image](https://user-images.githubusercontent.com/30671636/211154471-33ea1816-5344-4925-9cbe-130f06bdfc7d.png)

and my code

![image](https://user-images.githubusercontent.com/30671636/211154494-9bca042b-5e24-41d2-8086-241a25ebfa5a.png)

**Comment by itzzpadre** [comment]
Hi I had an email saying I was mentioned  but  can't see any response
