### ISSUE TITLE
Language prefix

### ISSUE THREAD

**Issue by hroma** [miladrahimi/phprouter#50]
Hi, 
Is there a way to handle multi language?
Thanks

**Comment by miladrahimi** [comment]
It's a router, not a framework, you can define different routes for different languages.

**Comment by hroma** [comment]
Ok. I'll go with [Bramus Router](https://github.com/bramus/router) .
A router (not a framework) that handle multilingual route out of the box...
Thank you for pointing out that a router is not a framework. I've learned something today.
