### ISSUE TITLE
Use Template engine as service?

### ISSUE THREAD

**Issue by URSELF-FR** [miladrahimi/phprouter#7]
Hi,

Thanks for your amazing router, I use it in my project and it's really good!
But I am using Twig templating and I was thinking of a way to incorporate it to your router? Is there any way to add it as a service or something like this and in this way I could render my view in my controller?

Thanks for your work.

**Comment by miladrahimi** [comment]
Why don't you return Twig response in your route or controller simply?

```
require "vendor/autoload.php";

$router = new \MiladRahimi\PHPRouter\Router();

$router->get('/', function () {
    $loader = new Twig_Loader_Filesystem('/path/to/themes');
    $twig = new Twig_Environment($loader);

    return $twig->render('theme.html');
});

$router->dispatch();
```

You are free to use any kind of architecture for your project.
